services:
  postgres:
    image: postgres:15-alpine
    # command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: deanslist-platform
      POSTGRES_USER: deanslist-platform
      POSTGRES_PASSWORD: deanslist-platform
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
